### ISSUE TITLE
【依頼】ProtoSpace挙動確認

### ISSUE THREAD

**Issue by lynxlevin** [lynxlevin/protospace-31051#1]
https://protospace-31051.herokuapp.com/

**Comment by tnk1215** [comment]
ご提出ありがとうございます！
挙動確認させて頂いたところ、1点のみ不備が見受けられましたので修正をお願いします！

【修正箇所】
**・コメント欄が空の状態で「送信する」を押下すると添付画像のエラーが出てしまう**
→空のコメントをした際に「コメントが保存されず、かつエラーが出ない状態」になるよう修正をお願い致します。

修正し次第、以下のprotospace完了報告フォームを再度提出お願いします！
※新しいissueを作っていただく必要はありません
https://forms.gle/ZdLeprTTWhMA8aZA7

![スクリーンショット 2020-10-16 17 56 05](https://user-images.githubusercontent.com/63444423/96238532-9231f700-0fd9-11eb-90d6-483ed636a5b5.png)

**Comment by lynxlevin** [comment]
修正いたしました。
お手数をおかけしますが、再度ご確認下さい

**Comment by airraid714** [comment]
ご提出ありがとうございます！
挙動確認させて頂きましたが、全く問題ございませんでしたのでLGTMとさせて頂きます🎉
おめでとうございます！

別途、最終課題の案内をチャンネルの方に送信させて頂きます。
今しばらくお待ちください。
